"""add repository branch analysis_run tables

Revision ID: f2907675422f
Revises: 
Create Date: 2026-09-05 20:15:45.902097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2907675422f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repositories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('default_branch', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('visibility', sa.String(), nullable=False),
    sa.Column('primary_language', sa.String(), nullable=True),
    sa.Column('license_name', sa.String(), nullable=True),
    sa.Column('stargazers_count', sa.Integer(), nullable=False),
    sa.Column('forks_count', sa.Integer(), nullable=False),
    sa.Column('open_issues_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'owner', 'name', name='uq_repository_provider_owner_name')
    )
    op.create_index(op.f('ix_repositories_owner'), 'repositories', ['owner'], unique=False)
    op.create_index(op.f('ix_repositories_provider'), 'repositories', ['provider'], unique=False)
    op.create_table('branches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repository_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('head_commit_sha', sa.String(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'name', name='uq_branch_repository_name')
    )
    op.create_index(op.f('ix_branches_repository_id'), 'branches', ['repository_id'], unique=False)
    op.create_table('analysis_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repository_id', sa.String(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('requested_branch', sa.String(), nullable=True),
    sa.Column('commit_sha', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('last_error', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analysis_run_repository_branch', 'analysis_runs', ['repository_id', 'branch_id'], unique=False)
    op.create_index(op.f('ix_analysis_runs_repository_id'), 'analysis_runs', ['repository_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analysis_runs_repository_id'), table_name='analysis_runs')
    op.drop_index('ix_analysis_run_repository_branch', table_name='analysis_runs')
    op.drop_table('analysis_runs')
    op.drop_index(op.f('ix_branches_repository_id'), table_name='branches')
    op.drop_table('branches')
    op.drop_index(op.f('ix_repositories_provider'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_owner'), table_name='repositories')
    op.drop_table('repositories')
    # ### end Alembic commands ###
